apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Kb2EPmpSmimzMse5102hdmffh3usk6QO7h7k17Rm3BpYSgZM1J9hEWA0tZ+2E000dsBnjIiVtxEioWOUYF4GMA==,iv:Md6PVscpNdS6dc1mTOD+I5gzmwvF3/HMFhbD3+0K5g4=,tag:k/n9XXovETa5IG/shM7l5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZkdOeTk1SldLVWhCYjBi
            T0xicGFuckZrMnRyd3FDUVRLaWE4NGEzVXhzCjU1K1RaUFFSWTV1UUhZM3FWOC9G
            ZTArVlgrWkhlTE5PNUtLejZPUzltQ2MKLS0tIERjYU9uL3owSnBZRjcxUktyVXhX
            Nkx5QW9RVERremhzRFVwaytRWEdzeEEKFp9TowRWSm8lzph47zenmwlI0/POF+ns
            T3Ksfp9AGfZsyN7AbQ5Kh5IOJQ4gxgbq+kuLHvMAv8ekXvia85N8Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:40:47Z"
    mac: ENC[AES256_GCM,data:SCep3XHt6PyUwK362plLAR+yNZXoOBgLqgI+TvKNMLsQVPHHPCQ7dA687aobE5AlNwpULfwzceVHlxhRpxbffKCPukJlSvebI0NOJ3aA0J/5GHIoubkUsjyf0wISgNOBVV9sfMmrSePLn1cW1qq6qejZeO0tOxNMeAvI6YCI8QE=,iv:rV/PBdgZTvgtdCH8Kw7GTU2CzHdzxNcQKOMiHUn+cE4=,tag:KOr9j1MRF3wuM100eBDPmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
